# Date: 09/17/2024
# Author: Christian Varner
# Purpose: Implement a simple linear least square problem.

"""
    GaussianLeastSquares{T, S} <: AbstractNLPModel{T, S}

Represent a least squares problem where entries of `A` are generated by a standard gaussian.

# Fields
- `meta :: NLPModelMeta{T, S}`: structure implemented in NLPModels to store information about the problem. See documentation: https://jso.dev/NLPModels.jl/stable/guidelines/.
- `counters :: Counters`: structure implemented in NLPModels to count objective, gradient, and hessian evaluations. See documentation above.
- `A :: Array{T}`: matrix of the linear system generated by sampling each element from a standard normal.
- `b :: S`, constant vector in linear system generated by sampling an `xstar` from a standard normal and setting `b = A * xstar`.
- `order :: Int64`, number of continuous derivatives for the objective function up to a maximum of 2. 
"""
mutable struct GaussianLeastSquares{T, S} <: AbstractNLPModel{T, S}
    # NLPModel bare minimum
    meta :: NLPModelMeta{T, S}
    counters :: Counters

    # Data for linear system
    A :: Array{T}
    b :: S
    order :: Int64 # max(how many continuous derivatives, 2)
end

# constructor to generate a regression problem
function GaussianLeastSquares(nrow :: Int64, ncol :: Int64)

    A = randn(nrow, ncol)
    xstar = randn(ncol)
    b = A * xstar

    return GaussianLeastSquares{Float64, Vector{Float64}}(NLPModelMeta(ncol; x0 = zeros(ncol)), Counters(), A, b, 2)
end

# function to initialize data
function initialize(prog_data :: GaussianLeastSquares{T, S}) where S <: Vector{T} where T <: Real

    # compute and create storage for auxilary variables
    Asquared = prog_data.A' * prog_data.A
    Ab = prog_data.A' * prog_data.b

    function obj(prog_data :: GaussianLeastSquares{T, S}, x :: S) where S <: Vector{T} where T <: Real
        prog_data.counters.neval_obj += 1
        return .5 * norm(prog_data.A * x - prog_data.b) ^ 2
    end

    function grad!(g :: S, prog_data :: GaussianLeastSquares{T, S}, x :: S) where S <: Vector{T} where T <: Real
        prog_data.counters.neval_grad += 1
        mul!(g, Asquared, x)
        g .-= Ab
    end

    function hess!(H :: Array{T}, prog_data :: GaussianLeastSquares{T, S}, x :: S) where S <: Vector{T} where T <: Real
        prog_data.counters.neval_hess += 1
        H .= Asquared 
    end

    # return functions
    return obj, grad!, hess!
end