name = "OptimizationMethods"
uuid = "5d16ec4c-3308-46eb-bccb-6dfd9ce745e1"
authors = ["Vivak Patel <vivak.patel@wisc.edu>",
           "Christian Varner <cvarner@wisc.edu>",
           "Daniel Adrian Maldonado <maldonadod@anl.gov>"]
version = "0.0.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
